export const tickets = [
  {
    id: 6,
    department: "LINE 1",
    station: "SUB 2",
    reason: "Printer",
    status: "pending",
  },
  {
    id: 7,
    department: "LINE 2",
    station: "ME 3",
    reason: "No Internet",
    status: "ongoing",
  },
  {
    id: 8,
    department: "LINE 3",
    station: "TW5",
    reason: "Monitor",
    status: "resolved",
  },
  {
    id: 9,
    department: "LINE 4",
    station: "CIRCUIT",
    reason: "Others: Keyboard",
    status: "unresolve",
  },
  {
    id: 10,
    department: "LINE 6",
    station: "SUB 8",
    reason: "No Internet",
    status: "pending",
  },

  {
    id: 11,
    department: "LINE 7",
    station: "REWORK",
    reason: "Printer",
    status: "ongoing",
  },
  {
    id: 12,
    department: "LINE 8",
    station: "ME 2",
    reason: "Others: Mouse",
    status: "resolved",
  },
  {
    id: 13,
    department: "LINE 10",
    station: "TW3",
    reason: "Monitor",
    status: "unresolve",
  },
  {
    id: 14,
    department: "LINE 11",
    station: "SUB 4",
    reason: "No Internet",
    status: "pending",
  },
  {
    id: 15,
    department: "LINE 12",
    station: "CIRCUIT",
    reason: "Printer",
    status: "ongoing",
  },

  {
    id: 16,
    department: "LINE 13",
    station: "ME 5",
    reason: "Others: LAN Cable",
    status: "resolved",
  },
  {
    id: 17,
    department: "LINE 14",
    station: "TW8",
    reason: "Monitor",
    status: "pending",
  },
  {
    id: 18,
    department: "LINE 15",
    station: "SUB 6",
    reason: "No Internet",
    status: "unresolve",
  },
  {
    id: 19,
    department: "LINE 17",
    station: "REWORK",
    reason: "Printer",
    status: "ongoing",
  },
  {
    id: 20,
    department: "LINE 18",
    station: "ME 1",
    reason: "Others: CPU",
    status: "resolved",
  },

  {
    id: 21,
    department: "CUTTING & CRIMPING",
    station: "TW1",
    reason: "No Internet",
    status: "pending",
  },
  {
    id: 22,
    department: "CUTTING & CRIMPING",
    station: "SUB 9",
    reason: "Monitor",
    status: "ongoing",
  },
  {
    id: 23,
    department: "CUTTING & CRIMPING",
    station: "ME 4",
    reason: "Printer",
    status: "resolved",
  },
  {
    id: 24,
    department: "CUTTING & CRIMPING",
    station: "CIRCUIT",
    reason: "Others: Keyboard",
    status: "unresolve",
  },
  {
    id: 25,
    department: "CUTTING & CRIMPING",
    station: "TW7",
    reason: "No Internet",
    status: "pending",
  },

  {
    id: 26,
    department: "LINE 5",
    station: "SUB 11",
    reason: "Monitor",
    status: "ongoing",
  },
  {
    id: 27,
    department: "LINE 9",
    station: "ME 7",
    reason: "Printer",
    status: "resolved",
  },
  {
    id: 28,
    department: "LINE 16",
    station: "TW9",
    reason: "No Internet",
    status: "unresolve",
  },
  {
    id: 29,
    department: "LINE 2",
    station: "CIRCUIT",
    reason: "Others: Headset",
    status: "pending",
  },
  {
    id: 30,
    department: "LINE 3",
    station: "SUB 1",
    reason: "Monitor",
    status: "ongoing",
  },

  {
    id: 31,
    department: "LINE 4",
    station: "ME 8",
    reason: "No Internet",
    status: "resolved",
  },
  {
    id: 32,
    department: "LINE 6",
    station: "TW4",
    reason: "Printer",
    status: "pending",
  },
  {
    id: 33,
    department: "LINE 7",
    station: "SUB 12",
    reason: "Others: Mouse",
    status: "unresolve",
  },
  {
    id: 34,
    department: "LINE 8",
    station: "REWORK",
    reason: "Monitor",
    status: "ongoing",
  },
  {
    id: 35,
    department: "LINE 10",
    station: "ME 9",
    reason: "No Internet",
    status: "resolved",
  },

  {
    id: 36,
    department: "LINE 11",
    station: "TW10",
    reason: "Printer",
    status: "pending",
  },
  {
    id: 37,
    department: "LINE 12",
    station: "SUB 3",
    reason: "Others: UPS",
    status: "ongoing",
  },
  {
    id: 38,
    department: "LINE 13",
    station: "CIRCUIT",
    reason: "Monitor",
    status: "resolved",
  },
  {
    id: 39,
    department: "LINE 14",
    station: "ME 10",
    reason: "No Internet",
    status: "unresolve",
  },
  {
    id: 40,
    department: "LINE 15",
    station: "TW6",
    reason: "Printer",
    status: "pending",
  },

  {
    id: 41,
    department: "LINE 17",
    station: "SUB 7",
    reason: "Others: Network Switch",
    status: "ongoing",
  },
  {
    id: 42,
    department: "LINE 18",
    station: "REWORK",
    reason: "Monitor",
    status: "resolved",
  },
  {
    id: 43,
    department: "LINE 1",
    station: "ME 11",
    reason: "No Internet",
    status: "pending",
  },
  {
    id: 44,
    department: "LINE 2",
    station: "TW2",
    reason: "Printer",
    status: "unresolve",
  },
  {
    id: 45,
    department: "LINE 3",
    station: "SUB 13",
    reason: "Others: Keyboard",
    status: "ongoing",
  },

  {
    id: 46,
    department: "LINE 4",
    station: "ME 12",
    reason: "Monitor",
    status: "resolved",
  },
  {
    id: 47,
    department: "LINE 5",
    station: "TW11",
    reason: "No Internet",
    status: "pending",
  },
  {
    id: 48,
    department: "LINE 6",
    station: "CIRCUIT",
    reason: "Printer",
    status: "ongoing",
  },
  {
    id: 49,
    department: "LINE 7",
    station: "SUB 14",
    reason: "Others: CPU",
    status: "resolved",
  },
  {
    id: 50,
    department: "LINE 8",
    station: "ME 13",
    reason: "No Internet",
    status: "unresolve",
  },

  {
    id: 51,
    department: "LINE 9",
    station: "TW13",
    reason: "Monitor",
    status: "pending",
  },
  {
    id: 52,
    department: "LINE 10",
    station: "SUB 15",
    reason: "Printer",
    status: "ongoing",
  },
  {
    id: 53,
    department: "LINE 11",
    station: "ME 14",
    reason: "Others: Mouse",
    status: "resolved",
  },
  {
    id: 54,
    department: "LINE 12",
    station: "TW14",
    reason: "No Internet",
    status: "unresolve",
  },
  {
    id: 55,
    department: "LINE 13",
    station: "CIRCUIT",
    reason: "Monitor",
    status: "pending",
  },
];

export const departments = [
  { id: 1, name: "Cutting & Crimping" },
  { id: 2, name: "LINE 1" },
  { id: 3, name: "LINE 2" },
  { id: 4, name: "LINE 3" },
  { id: 5, name: "LINE 4" },
  { id: 6, name: "LINE 5" },
  { id: 7, name: "LINE 6" },
  { id: 8, name: "LINE 7" },
  { id: 9, name: "LINE 8" },
  { id: 10, name: "LINE 9" },
  { id: 11, name: "LINE 10" },
  { id: 12, name: "LINE 11" },
  { id: 13, name: "LINE 12" },
  { id: 14, name: "LINE 13" },
  { id: 15, name: "LINE 14" },
  { id: 16, name: "LINE 15" },
  { id: 17, name: "LINE 16" },
  { id: 18, name: "Airbag" },
  { id: 19, name: "Warehouse" },
];

export const stations = [
  { id: 1, name: "Sub 1" },
  { id: 2, name: "Sub 2" },
  { id: 3, name: "Sub 3" },
  { id: 4, name: "Sub 4" },
  { id: 5, name: "Sub 5" },
  { id: 6, name: "Sub 6" },
  { id: 7, name: "Sub 7" },
  { id: 8, name: "Sub 8" },
  { id: 9, name: "Sub 9" },
  { id: 10, name: "Sub 10" },
  { id: 11, name: "ME 1" },
  { id: 12, name: "ME 2" },
  { id: 13, name: "ME 3" },
  { id: 14, name: "ME 4" },
  { id: 15, name: "ME 5" },
  { id: 16, name: "ME 6" },
  { id: 17, name: "ME 7" },
  { id: 18, name: "ME 8" },
  { id: 19, name: "ME 9" },
  { id: 20, name: "ME 10" },
  { id: 21, name: "Product Inspection" },
  { id: 22, name: "Dimension" },
  { id: 23, name: "Packing" },
  { id: 24, name: "Swap-up" },
  { id: 25, name: "Rework" },
];

export const reasons = [
  { id: 1, name: "Network Connection" },
  { id: 2, name: "Zebra Printer" },
  { id: 3, name: "Printer" },
  { id: 4, name: "No Internet" },
  { id: 5, name: "System Slow" },
  { id: 6, name: "PC Not Booting" },
  { id: 7, name: "Monitor Issue" },
  { id: 8, name: "Scanner Problem" },
  { id: 9, name: "Label Printing Error" },
  { id: 10, name: "Software Installation" },
  { id: 11, name: "Access Request" },
  { id: 12, name: "Hardware Replacement" },
];
